dataSources:
  concepts:
    resolver: sparql
    location: sparql/concepts.rq
    source: input/input.ttl
  collection:
    resolver: sparql
    location: sparql/collection.rq
    source: input/input.ttl
  members:
    resolver: sparql
    location: sparql/members.rq
    source: input/input.ttl

templates:
  - template: template.md
    outputLocation: output/
