PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT ?prefLabel ?altLabel ?definition
WHERE {
  ?s a skos:Concept.
  ?s skos:prefLabel ?prefLabel.
  OPTIONAL {
    ?s skos:altLabel ?altLabel.
  }
  OPTIONAL {
    ?s skos:definition ?definition.
  }
}
